#!/bin/bash
# If remontoire is running, kill it.  Otherwise start it.

remontoire_PID=$(pidof remontoire)

if [ -z "$remontoire_PID" ]; then
    /usr/bin/remontoire -c ~/.config/i3/config  -t ~/.config/i3/remontoire.css &
else
    kill $remontoire_PID
fi
