#!/usr/bin/env bash

update-nvim-nightly () {
    curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage > ~/.local/bin/nvim
    chmod +x ~/.local/bin/nvim
    echo "nvim updated"
}
