#!/usr/bin/env bash

CURRENCY=${1:-USD}
URL="https://blockchain.info/ticker"

# 1 - left click, 2 - mid click, 3 - right click
case $BLOCK_BUTTON in
  1) notify-send "Updating price";;
  3) google-chrome https://www.coindesk.com/price/bitcoin;; 
esac

PRICE=$(curl -s https://blockchain.info/ticker|jq ".${CURRENCY}.last")

echo "${PRICE}"
