#!/usr/bin/env bash

CURRENCY=${1:-USD}
URL="http://api.nbp.pl/api/exchangerates/rates/c/"

# 1 - left click, 2 - mid click, 3 - right click
case $BLOCK_BUTTON in
  1) notify-send "Updating price";;
esac
PRICE=$(curl -s $URL${CURRENCY}|jq '.rates[0].bid')

echo "${PRICE}"
