#!/usr/bin/env bash

MOUNT_PATH=${1}
LABEL=${2:-}

if mountpoint -q "${MOUNT_PATH}"; then
    echo " ${LABEL}"  # short
    echo " ${LABEL}"  # long
    echo "#00FF00"  # color
else
    echo ""  # short
    echo ""  # long
    echo "#FF0000"  # color
fi

echo ""  # background
