#!/usr/bin/env bash

MOUNT_PATH=${1}

if mountpoint -q "${MOUNT_PATH}"; then
    echo " "  # short
    echo " "  # long
    echo "#00FF00"  # color
else
    echo ""  # short
    echo ""  # long
    echo "#FF0000"  # color
fi

echo ""  # background
