#!/usr/bin/env bash
entrypoint=~/NAS/
declare -A folders=( ["h"]="home" ["d"]="Dropbox" ["g"]="GoogleDrive" ["m"]="Multimedia" )
declare -A iscsi=( ["c"]="Workspace/p/cint" ["h"]="Workspace/p/hint" ["d"]="Workspace/develop" )

short=''
long=''

for folder in "${!folders[@]}"; do
    if mountpoint -q "${entrypoint}${folders[$folder]}"; then
        short=${short}${folder^^}
        long="${long} ${folders[$folder]^^}"
    else
        short=${short}${folder,,}
        long="${long} ${folders[$folder],,}"
    fi
done

short="${short}|"
long="${long}|"

for folder in "${!iscsi[@]}"; do
    if mountpoint -q "$HOME/${iscsi[$folder]}"; then
        short=${short}${folder^^}
        long="${long} ${iscsi[$folder]^^}"
    else
        short=${short}${folder,,}
        long="${long} ${iscsi[$folder],,}"
    fi
done

echo ${short}
echo ${short}
echo "#00FF00"  # color
echo "#000000"  # background
