#!/bin/sh
source ~/.config/screenlayout/setup.sh

setxkbmap -layout pl

# no speaker
xset -b
# set mouse speed
xset m 3/2 0

# disable mouse auto movements
# xinput  --set-prop " USB OPTICAL MOUSE" "Device Accel Constant Deceleration" 1.5

# hide mouse
unclutter -idle 3 -jitter 5 -noevents &

# dpms && screensaver
xset dpms 600 &
xautolock -time 30 -locker "/usr/bin/i3lock -f -i /home/onjin/Dropbox/backgrounds/plain/Painkillers_broken.png  -t" &
/usr/bin/redshift-gtk &
/usr/bin/rescuetime &

# on numlock
numlockx

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrdb ~/.Xresources

exec i3
