#!/bin/sh
source ~/.config/screenlayout/setup.sh

setxkbmap -layout pl

# no speaker
xset -b
# set mouse speed
xset m 3/2 0
# disable mouse auto movements
xinput  --set-prop " USB OPTICAL MOUSE" "Device Accel Constant Deceleration" 1.5

# hide mouse
unclutter -idle 3 -jitter 5 -noevents &

# on numlock
numlockx

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

exec cinnamon-session
