# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# settings
shopt -s cdspell        # Autocorrects cd misspellings
shopt -s cmdhist        # Save multi-line commands in history as single line
shopt -s dotglob        # Include dotfiles in pathname expansion
shopt -s expand_aliases # Expand aliases
shopt -s extglob        # Enable extended pattern-matching features
shopt -s histreedit     # Add failed commands to the bash history
shopt -s histappend     # Append each session's history to $HISTFILE
shopt -s histverify     # Edit a recalled history line before executing
shopt -s checkwinsize   # check winsize after every command

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac


PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# utilities
source "$XDG_CONFIG_HOME/bash/utils"

# aliases
source "$XDG_CONFIG_HOME/bash/aliases"

# completion
source "$XDG_CONFIG_HOME/bash/completion"

# theme
source "$XDG_CONFIG_HOME/bash/themes/base.theme.bash"
source "$XDG_CONFIG_HOME/bash/themes/current"

# dircolors for dark solarized gnome-terminal
eval `dircolors ~/.config/bash/dircolors`

stty stop undef

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f ${HOME}/node_modules/tabtab/.completions/serverless.bash ] && . ${HOME}/node_modules/tabtab/.completions/serverless.bash

# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f ${HOME}/node_modules/tabtab/.completions/sls.bash ] && . ${HOME}/node_modules/tabtab/.completions/sls.bash

# Source all extra functions
for func in "$XDG_CONFIG_HOME/bash/functions.d/"*; do
	source "$func"
done
unset func
# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
export CC=`type -p gcc`

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
. "$HOME/.cargo/env"
# eval "$(starship init bash)"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
