#!/usr/bin/env bash

export PREFIX=/usr

export ANDROID_HOME=$HOME/tools/android/adt-bundle-linux-x86_64-20131030/sdk
export PATH="$HOME/.local/bin:$HOME/node_modules/.bin:$PATH:bin:$HOME/bin:$ANDROID_HOME/tools"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
