#!/usr/bin/env bash

export PREFIX=/usr

export PATH="$HOME/.local/bin:$PATH:bin:$HOME/bin"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"
