#!/usr/bin/env bash
#LOG="$HOME/profile-invocations"
#date >> $LOG
#echo "-----" >>$LOG
#echo "Caller: $0" >>$LOG
#echo "DESKTOP_SESSION: $DESKTOP_SESSION" >>$LOG
#echo "GDMSESSION: $GDMSESSION" >>$LOG
#echo "HOME: $HOME" >>$LOG
#echo "XDG_CONFIG_HOME: $XDG_CONFIG_HOME" >>  $LOG
export XDG_CONFIG_HOME=$HOME/.config
source "$HOME/.config/bash/exports"
eval "$(~/.pyenv/bin/pyenv init --path)"
export PATH="$HOME/.poetry/bin:$PATH"
source "$XDG_CONFIG_HOME/bash/bashrc"
